// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TayinTalepAPI.Data;

#nullable disable

namespace TayinTalepAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250610092612_TalepTuruEklendi")]
    partial class TalepTuruEklendi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("TayinTalepAPI.Models.TayinTalebi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BasvuruTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DegerlendirilmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("DegerlendirmeNotu")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOnaylandi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SicilNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TalepDurumu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TalepEdilenAdliye")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TalepTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SicilNo");

                    b.ToTable("TayinTalepleri");
                });

            modelBuilder.Entity("TayinTalepAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IseBaslamaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("MevcutAdliye")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SicilNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SicilNo")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TayinTalepAPI.Models.TayinTalebi", b =>
                {
                    b.HasOne("TayinTalepAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("SicilNo")
                        .HasPrincipalKey("SicilNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
